source 'http://rubygems.org'

gem 'activerecord', '4.2.5', require: 'active_record'
gem 'sinatra-activerecord', require: 'sinatra/activerecord'

gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
gem 'json', '>=1.8.3'
gem 'pry-byebug'
gem 'pry-nav'
gem 'rack-test'
gem 'rake'
gem 'require_all'
gem 'rspec'
gem 'sinatra'
gem 'sqlite3'
gem 'tux'
